export const GENRES = [
  "Todo",
  "Acción",
  "Romance",
  "Seinen",
  "Deportes",
] as const;

export const MANGA = [
  {
    id: "1",
    title: "Berserk",
    year: "1989",
    author: "Kentaro Miura",
    genre: "Acción",
    score: "9.4",
    chapters: 374,
  },
  {
    id: "2",
    title: "Chainsaw Man",
    year: "2018",
    author: "Tatsuki Fujimoto",
    genre: "Acción",
    score: "8.7",
    chapters: 190,
  },
  {
    id: "3",
    title: "Vagabond",
    year: "1998",
    author: "Takehiko Inoue",
    genre: "Seinen",
    score: "9.2",
    chapters: 327,
  },
  {
    id: "4",
    title: "Horimiya",
    year: "2011",
    author: "Hero",
    genre: "Romance",
    score: "8.3",
    chapters: 122,
  },
  {
    id: "5",
    title: "Blue Lock",
    year: "2018",
    author: "Muneyuki Kaneshiro",
    genre: "Deportes",
    score: "8.2",
    chapters: 280,
  },
  {
    id: "6",
    title: "Kaguya-sama",
    year: "2015",
    author: "Aka Akasaka",
    genre: "Romance",
    score: "8.8",
    chapters: 281,
  },
  {
    id: "7",
    title: "One Piece",
    year: "1997",
    author: "Eiichiro Oda",
    genre: "Acción",
    score: "9.2",
    chapters: 1120,
  },
  {
    id: "8",
    title: "Naruto",
    year: "1999",
    author: "Masashi Kishimoto",
    genre: "Acción",
    score: "8.1",
    chapters: 700,
  },
  {
    id: "9",
    title: "Bleach",
    year: "2001",
    author: "Tite Kubo",
    genre: "Acción",
    score: "7.9",
    chapters: 686,
  },
  {
    id: "10",
    title: "Death Note",
    year: "2003",
    author: "Tsugumi Ohba",
    genre: "Seinen",
    score: "8.6",
    chapters: 108,
  },
  {
    id: "11",
    title: "Fullmetal Alchemist",
    year: "2001",
    author: "Hiromu Arakawa",
    genre: "Acción",
    score: "9.0",
    chapters: 116,
  },
  {
    id: "12",
    title: "Monster",
    year: "1994",
    author: "Naoki Urasawa",
    genre: "Seinen",
    score: "9.1",
    chapters: 162,
  },
  {
    id: "13",
    title: "20th Century Boys",
    year: "1999",
    author: "Naoki Urasawa",
    genre: "Seinen",
    score: "8.9",
    chapters: 249,
  },
  {
    id: "14",
    title: "Vinland Saga",
    year: "2005",
    author: "Makoto Yukimura",
    genre: "Seinen",
    score: "9.0",
    chapters: 218,
  },
  {
    id: "15",
    title: "Attack on Titan",
    year: "2009",
    author: "Hajime Isayama",
    genre: "Acción",
    score: "8.5",
    chapters: 139,
  },
  {
    id: "16",
    title: "Jujutsu Kaisen",
    year: "2018",
    author: "Gege Akutami",
    genre: "Acción",
    score: "8.4",
    chapters: 271,
  },
  {
    id: "17",
    title: "Demon Slayer",
    year: "2016",
    author: "Koyoharu Gotouge",
    genre: "Acción",
    score: "8.1",
    chapters: 205,
  },
  {
    id: "18",
    title: "My Hero Academia",
    year: "2014",
    author: "Kohei Horikoshi",
    genre: "Acción",
    score: "7.9",
    chapters: 430,
  },
  {
    id: "19",
    title: "Hunter x Hunter",
    year: "1998",
    author: "Yoshihiro Togashi",
    genre: "Acción",
    score: "9.0",
    chapters: 400,
  },
  {
    id: "20",
    title: "Yu Yu Hakusho",
    year: "1990",
    author: "Yoshihiro Togashi",
    genre: "Acción",
    score: "8.4",
    chapters: 175,
  },
  {
    id: "21",
    title: "Slam Dunk",
    year: "1990",
    author: "Takehiko Inoue",
    genre: "Deportes",
    score: "8.9",
    chapters: 276,
  },
  {
    id: "22",
    title: "Real",
    year: "1999",
    author: "Takehiko Inoue",
    genre: "Deportes",
    score: "8.7",
    chapters: 97,
  },
  {
    id: "23",
    title: "Haikyuu!!",
    year: "2012",
    author: "Haruichi Furudate",
    genre: "Deportes",
    score: "8.8",
    chapters: 402,
  },
  {
    id: "24",
    title: "Ashita no Joe",
    year: "1968",
    author: "Asao Takamori",
    genre: "Deportes",
    score: "8.6",
    chapters: 171,
  },
  {
    id: "25",
    title: "Hajime no Ippo",
    year: "1989",
    author: "George Morikawa",
    genre: "Deportes",
    score: "8.7",
    chapters: 1470,
  },
  {
    id: "26",
    title: "Eyeshield 21",
    year: "2002",
    author: "Riichiro Inagaki",
    genre: "Deportes",
    score: "8.3",
    chapters: 333,
  },
  {
    id: "27",
    title: "Captain Tsubasa",
    year: "1981",
    author: "Yoichi Takahashi",
    genre: "Deportes",
    score: "7.8",
    chapters: 396,
  },
  {
    id: "28",
    title: "Ping Pong",
    year: "1996",
    author: "Taiyo Matsumoto",
    genre: "Deportes",
    score: "8.5",
    chapters: 55,
  },
  {
    id: "29",
    title: "Kuroko no Basket",
    year: "2008",
    author: "Tadatoshi Fujimaki",
    genre: "Deportes",
    score: "8.0",
    chapters: 275,
  },
  {
    id: "30",
    title: "Fruits Basket",
    year: "1998",
    author: "Natsuki Takaya",
    genre: "Romance",
    score: "8.4",
    chapters: 136,
  },
  {
    id: "31",
    title: "Nana",
    year: "2000",
    author: "Ai Yazawa",
    genre: "Romance",
    score: "8.7",
    chapters: 84,
  },
  {
    id: "32",
    title: "Ao Haru Ride",
    year: "2011",
    author: "Io Sakisaka",
    genre: "Romance",
    score: "8.0",
    chapters: 51,
  },
  {
    id: "33",
    title: "Toradora!",
    year: "2007",
    author: "Yuyuko Takemiya",
    genre: "Romance",
    score: "8.1",
    chapters: 63,
  },
  {
    id: "34",
    title: "Your Lie in April",
    year: "2011",
    author: "Naoshi Arakawa",
    genre: "Romance",
    score: "8.6",
    chapters: 44,
  },
  {
    id: "35",
    title: "Kimi ni Todoke",
    year: "2005",
    author: "Karuho Shiina",
    genre: "Romance",
    score: "8.2",
    chapters: 124,
  },
  {
    id: "36",
    title: "Skip Beat!",
    year: "2002",
    author: "Yoshiki Nakamura",
    genre: "Romance",
    score: "8.5",
    chapters: 320,
  },
  {
    id: "37",
    title: "Ouran High School Host Club",
    year: "2002",
    author: "Bisco Hatori",
    genre: "Romance",
    score: "8.2",
    chapters: 83,
  },
  {
    id: "38",
    title: "Maison Ikkoku",
    year: "1980",
    author: "Rumiko Takahashi",
    genre: "Romance",
    score: "8.6",
    chapters: 161,
  },
  {
    id: "39",
    title: "Oshi no Ko",
    year: "2020",
    author: "Aka Akasaka",
    genre: "Seinen",
    score: "8.3",
    chapters: 166,
  },
  {
    id: "40",
    title: "Vagabond Sidestory",
    year: "2004",
    author: "Takehiko Inoue",
    genre: "Seinen",
    score: "8.0",
    chapters: 12,
  },
  {
    id: "41",
    title: "Pluto",
    year: "2003",
    author: "Naoki Urasawa",
    genre: "Seinen",
    score: "8.9",
    chapters: 65,
  },
  {
    id: "42",
    title: "Blame!",
    year: "1997",
    author: "Tsutomu Nihei",
    genre: "Seinen",
    score: "8.2",
    chapters: 65,
  },
  {
    id: "43",
    title: "Gantz",
    year: "2000",
    author: "Hiroya Oku",
    genre: "Seinen",
    score: "7.9",
    chapters: 383,
  },
  {
    id: "44",
    title: "Homunculus",
    year: "2003",
    author: "Hideo Yamamoto",
    genre: "Seinen",
    score: "8.1",
    chapters: 165,
  },
  {
    id: "45",
    title: "Oyasumi Punpun",
    year: "2007",
    author: "Inio Asano",
    genre: "Seinen",
    score: "9.0",
    chapters: 147,
  },
  {
    id: "46",
    title: "Solanin",
    year: "2005",
    author: "Inio Asano",
    genre: "Seinen",
    score: "8.3",
    chapters: 28,
  },
  {
    id: "47",
    title: "Dorohedoro",
    year: "2000",
    author: "Q Hayashida",
    genre: "Seinen",
    score: "8.7",
    chapters: 167,
  },
  {
    id: "48",
    title: "Kingdom",
    year: "2006",
    author: "Yasuhisa Hara",
    genre: "Seinen",
    score: "9.0",
    chapters: 820,
  },
  {
    id: "49",
    title: "Golden Kamuy",
    year: "2014",
    author: "Satoru Noda",
    genre: "Seinen",
    score: "8.8",
    chapters: 314,
  },
  {
    id: "50",
    title: "Sanctuary",
    year: "1990",
    author: "Sho Fumimura",
    genre: "Seinen",
    score: "8.4",
    chapters: 108,
  },
  {
    id: "51",
    title: "Tokyo Ghoul",
    year: "2011",
    author: "Sui Ishida",
    genre: "Acción",
    score: "8.0",
    chapters: 143,
  },
  {
    id: "52",
    title: "Fire Punch",
    year: "2016",
    author: "Tatsuki Fujimoto",
    genre: "Acción",
    score: "8.1",
    chapters: 83,
  },
  {
    id: "53",
    title: "Dragon Ball",
    year: "1984",
    author: "Akira Toriyama",
    genre: "Acción",
    score: "8.7",
    chapters: 519,
  },
  {
    id: "54",
    title: "JoJo's Bizarre Adventure",
    year: "1987",
    author: "Hirohiko Araki",
    genre: "Acción",
    score: "8.6",
    chapters: 950,
  },
  {
    id: "55",
    title: "Rurouni Kenshin",
    year: "1994",
    author: "Nobuhiro Watsuki",
    genre: "Acción",
    score: "8.3",
    chapters: 255,
  },
  {
    id: "56",
    title: "Claymore",
    year: "2001",
    author: "Norihiro Yagi",
    genre: "Acción",
    score: "8.2",
    chapters: 155,
  },
];

export type MangaEntry = (typeof MANGA)[number];

const LIST_NAMES = [
  "Reading",
  "Plan to read",
  "Completed",
  "Paused",
  "Dropped",
] as const;

export const MANGA_LISTS = LIST_NAMES.map((name, i) => ({
  name,
  entries: MANGA.filter((_, j) => j % LIST_NAMES.length === i),
}));

export const MANGA_DETAIL = {
  title: "Berserk",
  author: "Kentaro Miura",
  status: "En publicación",
  year: "1989",
  score: "9.4",
  genres: ["Acción", "Dark fantasy", "Seinen"],
  progress: 0.32,
  lastRead: "Cap. 120",
  synopsis:
    "Guts, un mercenario marcado por un destino cruel, recorre un mundo devastado en busca de venganza contra los demonios que le arrebataron todo. Una épica oscura sobre la voluntad humana frente a lo inevitable.",
};

export const CHAPTERS = Array.from({ length: 8 }, (_, i) => ({
  id: String(374 - i),
  title: `Capítulo ${374 - i}`,
  date: "12 sep 2025",
  read: i > 4,
}));

export const STATS = [
  { label: "Capítulos", value: "374" },
  { label: "Volúmenes", value: "42" },
  { label: "Puntuación", value: "9.4" },
];
