query MangaList($userId: Int!, $status: MediaListStatus!) {
  MediaListCollection(
    userId: $userId
    type: MANGA
    status: $status
    forceSingleCompletedList: true
  ) {
    lists {
      entries {
        ...MangaListEntry
        media {
          ...MangaMedia
        }
      }
    }
  }
}
