mutation SaveMangaTracking(
  $id: Int
  $mediaId: Int
  $status: MediaListStatus
  $progress: Int
  $score: Float
  $startedAt: FuzzyDateInput
  $completedAt: FuzzyDateInput
) {
  SaveMediaListEntry(
    id: $id
    mediaId: $mediaId
    status: $status
    progress: $progress
    score: $score
    startedAt: $startedAt
    completedAt: $completedAt
  ) {
    id
    ...MangaTracking
  }
}

mutation DeleteMangaTracking($id: Int!) {
  DeleteMediaListEntry(id: $id) {
    deleted
  }
}
