query MangaListCounts($userId: Int!) {
  MediaListCollection(
    userId: $userId
    type: MANGA
    forceSingleCompletedList: true
  ) {
    lists {
      status
      isCustomList
      entries {
        id
      }
    }
  }
}
