query MangaList($userId: Int!, $status: MediaListStatus!) {
  MediaListCollection(
    userId: $userId
    type: MANGA
    status: $status
    forceSingleCompletedList: true
  ) {
    lists {
      entries {
        id
        progress
        score
        startedAt {
          year
          month
          day
        }
        completedAt {
          year
          month
          day
        }
        notes
        media {
          id
          title {
            userPreferred
            english
            romaji
            native
          }
          coverImage {
            large
            medium
            color
          }
          startDate {
            year
          }
          genres
          chapters
        }
      }
    }
  }
}
