fragment MangaListEntry on MediaList {
  status
  progress
  score
  startedAt {
    year
    month
    day
  }
  completedAt {
    year
    month
    day
  }
  notes
}

fragment MangaMedia on Media {
  title {
    userPreferred
    english
    romaji
    native
  }
  coverImage {
    large
    medium
    color
  }
  startDate {
    year
  }
  genres
  chapters
  mediaListEntry {
    id
    progress
  }
}

fragment MangaDetail on Media {
  ...MangaMedia
  status
  description
  mediaListEntry {
    id
    ...MangaListEntry
  }
  staff(perPage: 6, sort: RELEVANCE) {
    edges {
      role
      node {
        id
        name {
          full
        }
      }
    }
  }
}
